baseurl = "/"
title = "openGauss"
theme = "project"
themesDir = "./themes"

disablePathToLower = true
enableRobotsTXT = true
# Site language. Available translations in the theme's `/i18n` directory.
languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

uglyURLs = true
buildFuture = true

# Define the number of posts per page
paginate = 10



[menu]

# Main menu

#[[menu.main]]
#    identifier="home"
#    name = "Home"
#    url  = "/en/"
#    weight = 1

[[menu.main]]
    identifier = "download"
    name = "Download"
    weight = 2
    hasChidren = true


[[menu.main]]
    identifier = "software"
    name = "Software Package"
    url  = "/en/download.html"
    weight = 1
    parent = "download"

[[menu.main]]
    identifier = "supportTool"
    name = "Support Tools"
    url  = "/en/supportTools.html"
    weight = 2
    parent = "download"

[[menu.main]]
    identifier = "docs"
    name = "Docs"
    url  = "/en/docs/3.0.0/docs/BriefTutorial/BriefTutorial.html"
    weight = 3

[[menu.main]]
    identifier = "community"
    name = "Community"
    weight = 4
    hasChidren = true

[[menu.main]]
    identifier = "contribution"
    name = "Contribution"
    url  = "/en/contribution.html"
    weight = 1
    parent = "community"

[[menu.main]]
    identifier = "communication"
    name = "Communication"
    url  = "/en/community/onlineCommunication.html"
    weight = 2
    parent = "community"

[[menu.main]]
    identifier = "member"
    name = "Organization"
    url  = "/en/member.html"
    weight = 3
    parent = "community"
 
[[menu.main]]
    identifier = "datastat"
    name = "Statistics"
    url  = "https://datastat.opengauss.org/en/overview"
    weight = 4
    parent = "community"






#[[menu.main]]
#    identifier = "mailingList"
#    name = "Mailing List"
#    url  = "/en/community/mails.html"
#    weight = 6
#    parent = "community"

[[menu.main]]
    identifier = "connect"
    name = "Connect"
    weight = 5
    hasChidren = true

[[menu.main]]
    identifier = "news"
    name = "News"
    url  = "/en/news.html"
    weight = 1
    parent = "connect"

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url  = "/en/blogs/blogs.html"
    weight = 2
    parent = "connect"

[[menu.main]]
    identifier = "events"
    name = "Events"
    url  = "/en/events.html"
    weight = 3
    parent = "connect"

[[menu.main]]
    identifier = "video"
    name = "Videos"
    url = "/en/video.html"
    weight = 4
    parent = "connect"
 
[[menu.main]]
    identifier = "certification"
    name = "Certification"
    weight = 6
    hasChidren = true

[[menu.main]]
    identifier = "distribution"
    name = "Distribution Certification"
    url = "/en/certification.html"
    weight = 1
    parent = "certification"

[[menu.main]]
    identifier = "searching"
    name = "Query Certificates"
    url = "/en/training/search.html"
    weight = 2
    parent = "certification"

[[menu.main]]
    identifier = "security"
    name = "Security"
    weight = 7
    hasChidren = true

[[menu.main]]
    identifier = "vulnerability-report"
    name = "Vulnerability Report"
    url  = "/en/security.html"
    weight = 1
    parent = "security"

[[menu.main]]
    identifier = "security-advisories"
    name = "Security Advisories"
    url  = "/en/security-advisories.html"
    weight = 2
    parent = "security"

[[menu.main]]
    identifier = "cve"
    name = "CVE"
    url  = "/en/cve.html"
    weight = 3
    parent = "security"

[[menu.main]]
    identifier = "code"
    name = "Code"
    weight = 8
    hasChidren = true

[[menu.main]]
    identifier = "gitee"
    name = "Gitee"
    url = "https://gitee.com/opengauss"
    weight = 1
    parent = "code"

[[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/opengauss-mirror"
    weight = 2
    parent = "code"

#[[menu.main]]
#    identifier = "forum"
#   name = "Forum"
#   url = "https://bbs.huaweicloud.com/forum/forum-923-1.html"
#    weight = 13



#[[menu.main]]
#    identifier = "join"
#    name = "Join Us"
#    url = "mailto:contact@opengauss.org"
#    weight = 13

[[menu.main]]
    identifier = "lang"
    name = "中"
    url  = "/zh/"
    weight = 8


# Menu chinese
#[[languages.zh.menu.main]]
#    dentifier="home"
#    name = "主页"
#    url  = "/zh/"
#    weight = 1

[[languages.zh.menu.main]]
    identifier="download"
    name = "下载"
    weight = 2
    hasChidren = true

[[languages.zh.menu.main]]
    identifier="software"
    name = "软件包"
    url  = "/zh/download.html"
    weight = 1
    parent = "download"

[[languages.zh.menu.main]]
    identifier="supportTool"
    name = "支持工具"
    url  = "/zh/supportTools.html"
    weight = 2
    parent = "download"

[[languages.zh.menu.main]]
    identifier = "docs"
    name = "文档"
    url  = "/zh/docs/3.0.0/docs/BriefTutorial/BriefTutorial.html"
    weight = 3

[[languages.zh.menu.main]]
    identifier = "community"
    name = "社区"
    weight = 4
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "contribution"
    name = "社区贡献"
    url  = "/zh/contribution.html"
    weight = 1
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "communications"
    name = "线上交流"
    url  = "/zh/community/onlineCommunication.html"
    weight = 2
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "member"
    name = "社区组织"
    url  = "/zh/member.html"
    weight = 4
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "datastat"
    name = "贡献看板"
    url  = "https://datastat.opengauss.org/zh/overview"
    weight = 5
    parent = "community"

[[languages.zh.menu.main]]
    identifier = "userPractice"
    name = "用户实践"
    url  = "/zh/userPractice.html"
    weight = 6
    parent = "community"


[[languages.zh.menu.main]]
    identifier = "connect"
    name = "互动"
    weight = 5
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "news"
    name = "新闻"
    url  = "/zh/news.html"
    weight = 1
    parent = "connect"

[[languages.zh.menu.main]]
    identifier = "blog"
    name = "博客"
    url  = "/zh/blogs/blogs.html"
    weight = 2
    parent = "connect"


[[languages.zh.menu.main]]
    identifier = "events"
    name = "活动"
    url  = "/zh/events.html"
    weight = 3
    parent = "connect"

[[languages.zh.menu.main]]
    identifier = "video"
    name = "视频"
    url = "/zh/video.html"
    weight = 4
    parent = "connect"

[[languages.zh.menu.main]]
    identifier = "summit"
    name = "峰会"
    url = "/zh/summit.html"
    weight = 5
    parent = "connect"

[[languages.zh.menu.main]]
    identifier = "certification"
    name = "认证"
    weight = 6
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "distribution"
    name = "发行版认证"
    url = "/zh/certification.html"
    weight = 1
    parent = "certification"

[[languages.zh.menu.main]]
    identifier = "training"
    name = "培训认证"
    url = "/zh/training.html"
    weight = 2
    parent = "certification"

[[languages.zh.menu.main]]
    identifier = "searching"
    name = "证书查询"
    url = "/zh/training/search.html"
    weight = 3
    parent = "certification"

[[languages.zh.menu.main]]
    identifier = "security"
    name = "安全"
    weight = 7
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "vulnerability-report"
    name = "漏洞管理"
    url  = "/zh/security.html"
    weight = 1
    parent = "security"

[[languages.zh.menu.main]]
    identifier = "security-advisories"
    name = "安全公告"
    url  = "/zh/security-advisories.html"
    weight = 2
    parent = "security"

[[languages.zh.menu.main]]
    identifier = "cve"
    name = "CVE"
    url  = "/zh/cve.html"
    weight = 3
    parent = "security"

[[languages.zh.menu.main]]
    identifier = "code"
    name = "代码"
    weight = 8
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "gitee"
    name = "Gitee"
    url = "https://gitee.com/opengauss"
    weight = 1
    parent = "code"

[[languages.zh.menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/opengauss-mirror"
    weight = 2
    parent = "code"

[[languages.zh.menu.main]]
    identifier = "knowledgemain"
    name = "知识"
    weight = 18
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "knowledge"
    name = "知识图谱"
    weight = 19
    url  = "/zh/knowledge.html"
    hasChidren = false
    parent = "knowledgemain"

[[languages.zh.menu.main]]
    identifier = "advanced"
    name = "学习进阶"
    weight = 20
    url  = "/zh/advanced.html"
    hasChidren = false
    parent = "knowledgemain"

[[languages.zh.menu.main]]
    identifier = "mooc"
    name = "慕课平台"
    weight = 21
    url  = "https://moocstudio.opengauss.org"
    hasChidren = false
    parent = "knowledgemain"    

#[[languages.zh.menu.main]]
#    identifier = "forum"
#    name = "论坛"
#   url = "https://bbs.huaweicloud.com/forum/forum-923-1.html"
#    weight = 13


# [[languages.zh.menu.main]]
#    identifier = "join"
#   name = "加入我们"
#    url = "mailto:contact@opengauss.org"
#    weight = 13

[[languages.zh.menu.main]]
    identifier = "lang"
    name = "EN"
    url  = "/en/"
    weight = 8
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "en"
    name = "English"
    url  = "/en/"
    weight = 16
    parent = "lang"

[[languages.zh.menu.main]]
    identifier = "zh"
    name = "简体中文"
    url  = "/zh/"
    weight = 17
    parent = "lang"



# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "wechat"
    conc = "/zh/docs/qrCode.html"

[[languages.zh.menu.topbar]]
    weight = 1
    name = "微信"
    conc = "/zh/docs/qrCode.html"



[params]
    viewMorePostLink = "/news/"
    author = "Site template made by devcows Modified by openGauss team"
    defaultKeywords = ["openGauss","open source", "enterprise-grade", "relational database","community"]
    defaultDescription = "openGauss is an enterprise-grade open source relational database with high-performance, high-security, high-reliability. openGauss is also an open source database platform that encourages community contribution and collaboration."
    timestamp = "20201228"

    # Twitter
    # twitter = "GoHugoIO"
    # twitterImage = "img/twitter-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Enable the contact form by entering your Formspree.io email
    email = "contact@opengauss.org"
    contact_form_ajax = false

    about_us = "<p>We are an open source orgnization provides open source software.</p>"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    logo = "img/opengauss.svg"
    logo_small = "img/opengauss.svg"
    address = """<p><strong>opengauss.org</strong>
        <br>
        <br>Newtown upon River
        <br>Beijing
        <br>
        <strong>China</strong>
      </p>
      """
    #latitude = "-12.043333"
    #longitude = "-77.028333"
    
    ### DOC Configurations
    BookRepo = 'https://gitee.com/opengauss/docs/blob'
    BookEditPath= 'blob/master/content'
    BookDateFormat = 'Jan 2, 2019'
    enableGitInfo = true
    BookMenuBundle = '/menu'
    bookHidden = true
    bookFlatSection = true
    BookMenuBundleActiveLinkColor = '\#004ed0'

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[taxonomies]
  styles = "styles"
  tag = "tags"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to contribute?"
    subtitle = "We apprecite your contribution, whill all related projects are open source."
    link_url = "https://gitee.com/opengauss/"
    link_text = "Go To Source"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Partners"
    subtitle = ""


[params.recent_posts]
    enable = true
    title = "From our news"
    subtitle = "There are many events ocur since we announce open source, Please keep an your eye on us."

[params.copyright]
    enable = true
    text = "<a href=\"/en/trademark.html\">Trademark</a><span class='line-footer'>|</span><a href=\"/en/privacyPolicy.html\">Privacy Policy</a><span class='line-footer'>|</span><a href=\"/en/legal.html\">Legal Notice</a><span class='line-footer'>|</span><a href=\"/en/aboutUs.html\">About Us</a><span class='line-footer'>|</span><a href=\"https://status.opengauss.org\" target='_blank'>Service Status</a>"

[params.rightText]
    enable = true
    text = "Copyright © openGauss 2022. All rights reserved."

[languages.zh.params.copyright]
    enable = true
    text = "<a href=\"/zh/trademark.html\">品牌</a><span class='line-footer'>|</span><a href=\"/zh/privacyPolicy.html\">隐私政策</a><span class='line-footer'>|</span><a href=\"/zh/legal.html\">法律声明</a><span class='line-footer'>|</span><a href=\"/zh/aboutUs.html\">关于我们</a><span class='line-footer'>|</span><a href=\"https://status.opengauss.org\" target='_blank'>服务状态</a>"

[languages.zh.params.rightText]
    enable = true
    text = "版权所有 © openGauss 2022 保留一切权利"

[languages]

[languages.en]
    languageCode = "en-us"
    contentDir = "content/en"

[languages.zh]
    languageCode = "zh-cn"
    contentDir = "content/zh"

