baseurl = "/"
title = "openGauss"
theme = "project"
themesDir = "./themes"

disablePathToLower = true

# Site language. Available translations in the theme's `/i18n` directory.
languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

uglyURLs = true
buildFuture = true

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/en"
    weight = 1

[[menu.main]]
    identifier = "community"
    name = "Community"
    url  = "/en/community.html"
    weight = 2


[[menu.main]]
    identifier = "docs"
    name = "Docs"
    url  = "/en/docs.html"
    weight = 5
    hasChidren = true

[[menu.main]]
    identifier = "download"
    name = "Download"
    url  = "/en/download.html"
    weight = 6

[[menu.main]]
    identifier = "security"
    name = "Security"
    url  = "/en/security.html"
    weight = 7

[[menu.main]]
    identifier = "join"
    name = "Join Us"
    url = "mailto:contact@opengauss.org"
    weight = 8

[[menu.main]]
    identifier = "lang"
    name = "English"
    weight = 9
    hasChidren = true

[[menu.main]]
    identifier = "zh"
    name = "简体中文"
    url  = "/zh"
    weight = 11
    parent = "lang"

[[menu.main]]
    identifier = "en"
    name = "English"
    url  = "/en"
    weight = 12
    parent = "lang"


# Menu chinese
[[languages.zh.menu.main]]
    dentifier="home"
    name = "首页"
    url  = "/zh"
    weight = 1

[[languages.zh.menu.main]]
    identifier = "community"
    name = "社区"
    url  = "/zh/docs/community.html"
    weight = 2

[[languages.zh.menu.main]]
    identifier = "docs"
    name = "文档"
    url  = "/zh/docs/home.html"
    weight = 5
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "download"
    name = "下载"
    url  = "/zh/download.html"
    weight = 6

[[languages.zh.menu.main]]
    identifier = "security"
    name = "安全"
    url  = "/zh/security.html"
    weight = 7

[[languages.zh.menu.main]]
    identifier = "join"
    name = "加入我们"
    url = "mailto:contact@opengauss.org"
    weight = 8

[[languages.zh.menu.main]]
    identifier = "lang"
    name = "简体中文"
    weight = 9
    hasChidren = true

[[languages.zh.menu.main]]
    identifier = "en"
    name = "English"
    url  = "/en"
    weight = 11
    parent = "lang"

[[languages.zh.menu.main]]
    identifier = "zh"
    name = "简体中文"
    url  = "/zh"
    weight = 12
    parent = "lang"



# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://gitee.com/opengauss"
    pre = "<i class='fa fa-2x fa-github'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "openGauss"
    defaultKeywords = ["devows", "hugo", "go", "openGauss"]
    defaultDescription = "Site template made by devcows Modified by openGauss team"

    # Twitter
    # twitter = "GoHugoIO"
    # twitterImage = "img/twitter-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Enable the contact form by entering your Formspree.io email
    email = "contact@opengauss.org"
    contact_form_ajax = false

    about_us = "<p>We are an open source orgnization provides open source software.</p>"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    logo = "img/opengauss.png"
    logo_small = "img/opengauss.png"
    address = """<p><strong>opengauss.org</strong>
        <br>
        <br>Newtown upon River
        <br>Beijing
        <br>
        <strong>China</strong>
      </p>
      """
    #latitude = "-12.043333"
    #longitude = "-77.028333"
    
    ### DOC Configurations
    BookRepo = 'https://gitee.com/opengauss/docs'
    BookEditPath= 'blob/master/content'
    BookDateFormat = 'Jan 2, 2019'
    enableGitInfo = true
    BookMenuBundle = '/menu'
    bookHidden = true
    bookFlatSection = true

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to contribute?"
    subtitle = "We apprecite your contribution, whill all related projects are open source."
    link_url = "https://gitee.com/opengauss/"
    link_text = "Go To Source"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Partners"
    subtitle = ""


[params.recent_posts]
    enable = true
    title = "From our news"
    subtitle = "There are many events ocur since we announce open source, Please keep an your eye on us."

[params.copyright]
    enable = true
    text = "Copyright © openGauss 2020. All rights reserved.<br><a href=\"/en/legal.html\">Legal Notice</a>&nbsp;&nbsp;<a href=\"/en/privacyPolicy.html\">Privacy Policy</a>"

[languages.zh.params.copyright]
    enable = true
    text = "版权所有 © openGauss 2020 保留一切权利 <br><a href=\"/zh/legal.html\">法律声明</a>&nbsp;&nbsp;<a href=\"/zh/privacyPolicy.html\">隐私政策</a>"

[languages]

[languages.en]
    languageCode = "en-us"
    contentDir = "content/en"

[languages.zh]
    languageCode = "zh-cn"
    contentDir = "content/zh"
